### ISSUE TITLE
Missing License in Flutters showAboutDialog

### ISSUE THREAD

**Issue by stefan-kuhn** [ZaraclaJ/audio_recorder#60]
Thanks for your great work!

I just wanted to add this plugin to a project, but unfortunately, the _license is missing in the automatically generated licenses dialog in Android_.

For demonstration purpose, the source of a minimal example:

pubspec.yaml:
```yaml
name: arlicense
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_recorder: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

main.dart:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'ARLicense',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home: Scaffold(
            body: Center(
                child: Builder(
                    builder: (context) => FlatButton(
                        onPressed: () => showAboutDialog(context: context),
                        child: Text("showAboutDialog"))))));
  }
}
```

Steps to reproduce:
1. Click on `showAboutDialog`
2. Click on `View licenses`
3. Scroll down.
=> You will find
**audio_recorder
TODO: Add your license here.**

I saw, that you already added a license to the project (- I think it is BSD?) - but as shown above, it seems not working - at least for me.

Best regards
Stefan
